Repository kuzzleio/kuzzle-plugin-prometheus, pull requests merged in 2019-11, with the labels that each got.

#8 Remove useless Redis synchronization call
  README.md
  demo/prometheus.yml
  lib/PrometheusPlugin.js
  package-lock.json
  test/PrometheusPlugin.test.js
Labels: changelog:enhancements

#9 Release 1.2.1
  README.md
  demo/prometheus.yml
  lib/PrometheusPlugin.js
  package-lock.json
  package.json
  test/PrometheusPlugin.test.js
Labels: release

#10 Fix realtime subscription counter
  lib/PrometheusPlugin.js
  test/PrometheusPlugin.test.js
Labels: changelog:bug-fixes

#11 Release 1.2.2
  lib/PrometheusPlugin.js
  package-lock.json
  package.json
  test/PrometheusPlugin.test.js
Labels: release

#13 Remove Redis sync processes
  README.md
  lib/index.js
  test/PrometheusPlugin.test.js
Labels: changelog:enhancements

#12 Fix realtime subscription counter
  lib/index.js
  test/PrometheusPlugin.test.js
Labels: changelog:bug-fixes

#14 Release 2.0.1
  README.md
  lib/index.js
  package-lock.json
  package.json
  test/PrometheusPlugin.test.js
Labels: release
